### ISSUE TITLE
Issue with HTML5 

### ISSUE THREAD

**Issue by Drizzle42** [borup3/Lighting-System-2D#3] opened 2019-04-03 11:09 UTC
Hello, first off thanks a lot for sharing this great engine. It works great on windows but in HTML5 the lights don't seem to work, the shadowmap is present but lights don't appear. Since there is no error i have no idea how to fix this. (using runtime 2.2.1.291)

Thanks in advance

**Comment by borup3** [comment] 2019-04-03 13:06
Duplicate of #1

**Closed** 2020-06-15 01:45 UTC
